// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as ReactQuery from "react-query";

var client = new ReactQuery.QueryClient();

var element = document.querySelector("#root");

if (!(element == null)) {
  ReactDom.render(React.createElement(ReactQuery.QueryClientProvider, {
            client: client,
            children: React.createElement(App.make, {})
          }), element);
}

export {
  client ,
  
}
/* client Not a pure module */
